apiVersion: v1
kind: PersistentVolume
metadata:
  name: proxy-pv-nas
  labels:
    pv: proxy
spec:
  capacity:
    storage: 10Gi
  storageClassName: nas
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "alicloud/nas"
    options:
      server: "xxxxx.cn-hangzhou.nas.aliyuncs.com"
      path: "/test_log/douyinpay/.mitmproxy"
      vers: "3"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proxy-pvc-nas
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas
  resources:
    requests:
      storage: 10G
  selector:
    matchLabels:
      pv: proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
      annotations:
        k8s.aliyun.com/eci-use-specs: "ecs.c5.large"
        k8s.aliyun.com/eci-spot-strategy: "SpotAsPriceGo"
        k8s.aliyun.com/eci-with-eip: "true"
    spec:
      hostNetwork: true
      volumes:
        - name: my-pvc-nas
          persistentVolumeClaim:
            claimName: proxy-pvc-nas
      containers:
        - name: proxy
          image: dounine/mitmproxy:latest
          volumeMounts:
            - name: my-pvc-nas
              mountPath: "/home/mitmproxy/.mitmproxy"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8081
              name: https
              protocol: TCP
